# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gustav/Documents/dev/demo_tool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gustav/Documents/dev/demo_tool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/gustav/Documents/dev/demo_tool && $(CMAKE_COMMAND) -E cmake_progress_start /home/gustav/Documents/dev/demo_tool/CMakeFiles /home/gustav/Documents/dev/demo_tool/3pp/ImGuiGLFWstartingpoint//CMakeFiles/progress.marks
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3pp/ImGuiGLFWstartingpoint/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gustav/Documents/dev/demo_tool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3pp/ImGuiGLFWstartingpoint/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3pp/ImGuiGLFWstartingpoint/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3pp/ImGuiGLFWstartingpoint/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/gustav/Documents/dev/demo_tool && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/rule:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/rule
.PHONY : 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/rule

# Convenience name for target.
imgui: 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/rule

.PHONY : imgui

# fast build rule for target.
imgui/fast:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

imgui-docking/backends/imgui_impl_glfw.o: imgui-docking/backends/imgui_impl_glfw.cpp.o

.PHONY : imgui-docking/backends/imgui_impl_glfw.o

# target to build an object file
imgui-docking/backends/imgui_impl_glfw.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui-docking/backends/imgui_impl_glfw.cpp.o

imgui-docking/backends/imgui_impl_glfw.i: imgui-docking/backends/imgui_impl_glfw.cpp.i

.PHONY : imgui-docking/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui-docking/backends/imgui_impl_glfw.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui-docking/backends/imgui_impl_glfw.cpp.i

imgui-docking/backends/imgui_impl_glfw.s: imgui-docking/backends/imgui_impl_glfw.cpp.s

.PHONY : imgui-docking/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui-docking/backends/imgui_impl_glfw.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui-docking/backends/imgui_impl_glfw.cpp.s

imgui-docking/backends/imgui_impl_opengl3.o: imgui-docking/backends/imgui_impl_opengl3.cpp.o

.PHONY : imgui-docking/backends/imgui_impl_opengl3.o

# target to build an object file
imgui-docking/backends/imgui_impl_opengl3.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui-docking/backends/imgui_impl_opengl3.cpp.o

imgui-docking/backends/imgui_impl_opengl3.i: imgui-docking/backends/imgui_impl_opengl3.cpp.i

.PHONY : imgui-docking/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui-docking/backends/imgui_impl_opengl3.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui-docking/backends/imgui_impl_opengl3.cpp.i

imgui-docking/backends/imgui_impl_opengl3.s: imgui-docking/backends/imgui_impl_opengl3.cpp.s

.PHONY : imgui-docking/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui-docking/backends/imgui_impl_opengl3.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui-docking/backends/imgui_impl_opengl3.cpp.s

imgui-docking/imgui.o: imgui-docking/imgui.cpp.o

.PHONY : imgui-docking/imgui.o

# target to build an object file
imgui-docking/imgui.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui.cpp.o
.PHONY : imgui-docking/imgui.cpp.o

imgui-docking/imgui.i: imgui-docking/imgui.cpp.i

.PHONY : imgui-docking/imgui.i

# target to preprocess a source file
imgui-docking/imgui.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui.cpp.i
.PHONY : imgui-docking/imgui.cpp.i

imgui-docking/imgui.s: imgui-docking/imgui.cpp.s

.PHONY : imgui-docking/imgui.s

# target to generate assembly for a file
imgui-docking/imgui.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui.cpp.s
.PHONY : imgui-docking/imgui.cpp.s

imgui-docking/imgui_demo.o: imgui-docking/imgui_demo.cpp.o

.PHONY : imgui-docking/imgui_demo.o

# target to build an object file
imgui-docking/imgui_demo.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_demo.cpp.o
.PHONY : imgui-docking/imgui_demo.cpp.o

imgui-docking/imgui_demo.i: imgui-docking/imgui_demo.cpp.i

.PHONY : imgui-docking/imgui_demo.i

# target to preprocess a source file
imgui-docking/imgui_demo.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_demo.cpp.i
.PHONY : imgui-docking/imgui_demo.cpp.i

imgui-docking/imgui_demo.s: imgui-docking/imgui_demo.cpp.s

.PHONY : imgui-docking/imgui_demo.s

# target to generate assembly for a file
imgui-docking/imgui_demo.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_demo.cpp.s
.PHONY : imgui-docking/imgui_demo.cpp.s

imgui-docking/imgui_draw.o: imgui-docking/imgui_draw.cpp.o

.PHONY : imgui-docking/imgui_draw.o

# target to build an object file
imgui-docking/imgui_draw.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_draw.cpp.o
.PHONY : imgui-docking/imgui_draw.cpp.o

imgui-docking/imgui_draw.i: imgui-docking/imgui_draw.cpp.i

.PHONY : imgui-docking/imgui_draw.i

# target to preprocess a source file
imgui-docking/imgui_draw.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_draw.cpp.i
.PHONY : imgui-docking/imgui_draw.cpp.i

imgui-docking/imgui_draw.s: imgui-docking/imgui_draw.cpp.s

.PHONY : imgui-docking/imgui_draw.s

# target to generate assembly for a file
imgui-docking/imgui_draw.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_draw.cpp.s
.PHONY : imgui-docking/imgui_draw.cpp.s

imgui-docking/imgui_tables.o: imgui-docking/imgui_tables.cpp.o

.PHONY : imgui-docking/imgui_tables.o

# target to build an object file
imgui-docking/imgui_tables.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_tables.cpp.o
.PHONY : imgui-docking/imgui_tables.cpp.o

imgui-docking/imgui_tables.i: imgui-docking/imgui_tables.cpp.i

.PHONY : imgui-docking/imgui_tables.i

# target to preprocess a source file
imgui-docking/imgui_tables.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_tables.cpp.i
.PHONY : imgui-docking/imgui_tables.cpp.i

imgui-docking/imgui_tables.s: imgui-docking/imgui_tables.cpp.s

.PHONY : imgui-docking/imgui_tables.s

# target to generate assembly for a file
imgui-docking/imgui_tables.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_tables.cpp.s
.PHONY : imgui-docking/imgui_tables.cpp.s

imgui-docking/imgui_widgets.o: imgui-docking/imgui_widgets.cpp.o

.PHONY : imgui-docking/imgui_widgets.o

# target to build an object file
imgui-docking/imgui_widgets.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_widgets.cpp.o
.PHONY : imgui-docking/imgui_widgets.cpp.o

imgui-docking/imgui_widgets.i: imgui-docking/imgui_widgets.cpp.i

.PHONY : imgui-docking/imgui_widgets.i

# target to preprocess a source file
imgui-docking/imgui_widgets.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_widgets.cpp.i
.PHONY : imgui-docking/imgui_widgets.cpp.i

imgui-docking/imgui_widgets.s: imgui-docking/imgui_widgets.cpp.s

.PHONY : imgui-docking/imgui_widgets.s

# target to generate assembly for a file
imgui-docking/imgui_widgets.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/imgui_widgets.cpp.s
.PHONY : imgui-docking/imgui_widgets.cpp.s

imgui-docking/misc/freetype/imgui_freetype.o: imgui-docking/misc/freetype/imgui_freetype.cpp.o

.PHONY : imgui-docking/misc/freetype/imgui_freetype.o

# target to build an object file
imgui-docking/misc/freetype/imgui_freetype.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/misc/freetype/imgui_freetype.cpp.o
.PHONY : imgui-docking/misc/freetype/imgui_freetype.cpp.o

imgui-docking/misc/freetype/imgui_freetype.i: imgui-docking/misc/freetype/imgui_freetype.cpp.i

.PHONY : imgui-docking/misc/freetype/imgui_freetype.i

# target to preprocess a source file
imgui-docking/misc/freetype/imgui_freetype.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/misc/freetype/imgui_freetype.cpp.i
.PHONY : imgui-docking/misc/freetype/imgui_freetype.cpp.i

imgui-docking/misc/freetype/imgui_freetype.s: imgui-docking/misc/freetype/imgui_freetype.cpp.s

.PHONY : imgui-docking/misc/freetype/imgui_freetype.s

# target to generate assembly for a file
imgui-docking/misc/freetype/imgui_freetype.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/imgui-docking/misc/freetype/imgui_freetype.cpp.s
.PHONY : imgui-docking/misc/freetype/imgui_freetype.cpp.s

src/ImGui_init.o: src/ImGui_init.cpp.o

.PHONY : src/ImGui_init.o

# target to build an object file
src/ImGui_init.cpp.o:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/src/ImGui_init.cpp.o
.PHONY : src/ImGui_init.cpp.o

src/ImGui_init.i: src/ImGui_init.cpp.i

.PHONY : src/ImGui_init.i

# target to preprocess a source file
src/ImGui_init.cpp.i:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/src/ImGui_init.cpp.i
.PHONY : src/ImGui_init.cpp.i

src/ImGui_init.s: src/ImGui_init.cpp.s

.PHONY : src/ImGui_init.s

# target to generate assembly for a file
src/ImGui_init.cpp.s:
	cd /home/gustav/Documents/dev/demo_tool && $(MAKE) $(MAKESILENT) -f 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/build.make 3pp/ImGuiGLFWstartingpoint/CMakeFiles/imgui.dir/src/ImGui_init.cpp.s
.PHONY : src/ImGui_init.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... imgui"
	@echo "... imgui-docking/backends/imgui_impl_glfw.o"
	@echo "... imgui-docking/backends/imgui_impl_glfw.i"
	@echo "... imgui-docking/backends/imgui_impl_glfw.s"
	@echo "... imgui-docking/backends/imgui_impl_opengl3.o"
	@echo "... imgui-docking/backends/imgui_impl_opengl3.i"
	@echo "... imgui-docking/backends/imgui_impl_opengl3.s"
	@echo "... imgui-docking/imgui.o"
	@echo "... imgui-docking/imgui.i"
	@echo "... imgui-docking/imgui.s"
	@echo "... imgui-docking/imgui_demo.o"
	@echo "... imgui-docking/imgui_demo.i"
	@echo "... imgui-docking/imgui_demo.s"
	@echo "... imgui-docking/imgui_draw.o"
	@echo "... imgui-docking/imgui_draw.i"
	@echo "... imgui-docking/imgui_draw.s"
	@echo "... imgui-docking/imgui_tables.o"
	@echo "... imgui-docking/imgui_tables.i"
	@echo "... imgui-docking/imgui_tables.s"
	@echo "... imgui-docking/imgui_widgets.o"
	@echo "... imgui-docking/imgui_widgets.i"
	@echo "... imgui-docking/imgui_widgets.s"
	@echo "... imgui-docking/misc/freetype/imgui_freetype.o"
	@echo "... imgui-docking/misc/freetype/imgui_freetype.i"
	@echo "... imgui-docking/misc/freetype/imgui_freetype.s"
	@echo "... src/ImGui_init.o"
	@echo "... src/ImGui_init.i"
	@echo "... src/ImGui_init.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/gustav/Documents/dev/demo_tool && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

